[package]
name = "adapter_layer"
version = "0.1.0"
edition = "2021"
description = "層の外側。内側の層だけを呼ぶ"
license = "MIT"
repository = "https://github.com/daidaiiro/daidaiiro"
keywords = ["layer", "adapter"]
categories = ["development-tools"]
readme = "README.md"

[dependencies]
core_layer = { path = "../core", version = "0.1.0" }
